# Generated by Django 3.1.7 on 2021-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='pickem.Team'),
        ),
    ]
