# Generated by Django 3.1.7 on 2021-03-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0004_auto_20210328_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_number',
        ),
    ]
