# Generated by Django 3.1.7 on 2021-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0005_auto_20210328_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
