# Generated by Django 3.1.7 on 2021-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0010_remove_prediction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_pred_week',
            field=models.IntegerField(default=0),
        ),
    ]
