# Generated by Django 3.1.7 on 2021-03-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0011_userprofile_latest_pred_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_occurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='pickem.team'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='pickem.Team'),
        ),
    ]
