# Generated by Django 3.1.7 on 2021-04-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0013_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='date_time',
        ),
    ]
