# Generated by Django 3.1.7 on 2021-04-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0014_auto_20210401_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='w0g0', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='pickem.team'),
        ),
    ]
