# Generated by Django 3.1.7 on 2021-04-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0016_auto_20210401_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='predicted_all',
            field=models.BooleanField(default=False),
        ),
    ]
