# Generated by Django 3.1.7 on 2021-04-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0017_userprofile_predicted_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='predicted_all',
        ),
    ]
