# Generated by Django 3.1.7 on 2021-04-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0018_remove_userprofile_predicted_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.CharField(max_length=100),
        ),
    ]
