# Generated by Django 3.1.7 on 2021-04-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0021_auto_20210408_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_updates',
            field=models.BooleanField(default=False),
        ),
    ]
